name: packager

ghc-options:
  - -Wall
  - -Wno-name-shadowing

dependencies:
  - base
  - dhall
  - directory
  - filepath
  - getopt-generics
  - interpolate
  - shake
  - temporary
  - yaml

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - mockery
      - silently
      - string-conversions
    ghc-options:
      - -fdefer-typed-holes

executables:
  packager:
    main: Main.hs
    source-dirs:
      - app
      - src
