name: peck

ghc-options:
  - -Wall
  - -Wno-name-shadowing

dependencies:
  - aeson
  - base
  - data-default
  - dhall
  - directory
  - filepath
  - getopt-generics >= 0.13.1.0
  - interpolate
  - linux-namespaces
  - process
  - sqlite-simple
  - string-conversions
  - temporary
  - unix
  - yaml

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - mockery
      - shake
      - silently
    ghc-options:
      - -fdefer-typed-holes

executables:
  peck:
    main: Main.hs
    source-dirs:
      - app
      - src
